language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: supersnager@gmail.com
  api_key:
    secure: JxZ6tirIDdzAPsxZ8yFiREX9onToccZq/NwKeuP3huTCHJ0XeNXlHYdQoUNptYE3XUiTnR+Dc5S4mvxf1m81GXccA4RtVi8LyIxBGKa+yinqeAreYvzkiIHl69HcV7BJI1FOCQNwEy/S7+gOm3nlB8s8l4MHX9q6E9vUD+VjF1w4yzNiK4eSxkB4Y7PUjX5aDFonmwx5aZgiWtsK7N7HYXU7HPXjlzQud1bIe69LGeJH4J/GvYIWNoNcaFTj41m9H98ISMYzZEBA58ZaUWtMqVsX1M2KkOW1TlK7kbRwU0FKkoavf3aEU0Q0vpFOf3rW/HI3TshQ9apuQC6BvE4eDqOElM4cm+GcD2eg5pXmB6NP+i053FfvRhrJf6E2abRjBuZwT/sYseB0Qykd5hghO12P9aHQPJHwI5YA7h7prOcrTeg/qye64tweLEi6JLK6wYx/8xuphyVJbptSGhqBY5G7kQ8PCw/57NN8vYyFVgOtOZaY4ALuWzdjuVLB3Z2GPeMc2ZEMCMDghyaMgdqAM2napeGkArXeI6dBFxVNQaXlEw2MlzgGBynHBQP6RXpN7exZCblHvnEJdEaFw/0I9xFpKq5rkVXZuHHta9R9FhMeiblcFuyQFPSJLI1QzxQ4UlM2NlDZ44QXIYXygj1jx6LaL41hVPqTRN9YSj11ibU=
  skip_cleanup: true
  on:
    tags: true
    branch: master
